const INITIAL_ANNONCES = [
  {
    "id": "a001",
    "prix": 35900,
    "origine": "France",
    "autopilot": "🥈 Autopilot amélioré",
    "processeur": "Ryzen (confirmé)",
    "modele": "Performance",
    "couleur": "Noir",
    "coutImportation": 0,
    "kilometrage": 38034,
    "interieur": "",
    "soh": 0.96,
    "remarques": "EAP + Ryzen + HW3 confirmés, SOH 96%, TVA récup. (leboncoin, GT Auto)",
    "lien": "https://www.leboncoin.fr/ad/voitures/3206448348",
    "score": 71,
    "prixTotal": 35900,
    "localisation": "Niderviller (Moselle) ~50 km",
    "optionEap": "EAP inclus ✓",
    "covering": 0,
    "budgetToutCompris": 35900,
    "fsd24": 1176,
    "budget2ansFsd": 37076,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a002",
    "prix": 29950,
    "origine": "Allemagne",
    "autopilot": "🥇 FSD",
    "processeur": "Ryzen probable (à confirmer)",
    "modele": "LR AWD",
    "couleur": "Bleue",
    "coutImportation": 2000,
    "kilometrage": 54000,
    "interieur": "Blanc",
    "soh": null,
    "remarques": "",
    "lien": "https://suchen.mobile.de/auto-inserat/x/458656284.html",
    "score": 68.2,
    "prixTotal": 31950,
    "localisation": "Norderstedt (Hambourg) ~720 km +livr.",
    "optionEap": "FSD inclus ✓",
    "covering": 0,
    "budgetToutCompris": 31950,
    "fsd24": 0,
    "budget2ansFsd": 31950,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a003",
    "prix": 30821,
    "origine": "Allemagne",
    "autopilot": "🥈 Autopilot amélioré",
    "processeur": "Ryzen",
    "modele": "LR AWD",
    "couleur": "Grise",
    "coutImportation": 1500,
    "kilometrage": 46227,
    "interieur": "Noir",
    "soh": 0.93,
    "remarques": "",
    "lien": "https://suchen.mobile.de/auto-inserat/x/459356789.html",
    "score": 66.1,
    "prixTotal": 32321,
    "localisation": "Seesen (Basse-Saxe) ~460 km",
    "optionEap": "EAP inclus ✓",
    "covering": 0,
    "budgetToutCompris": 32321,
    "fsd24": 1176,
    "budget2ansFsd": 33497,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a004",
    "prix": 28990,
    "origine": "France",
    "autopilot": "🥈 Autopilot amélioré",
    "processeur": "Ryzen (probable)",
    "modele": "LR AWD",
    "couleur": "Noire",
    "coutImportation": 0,
    "kilometrage": 60228,
    "interieur": "Noir",
    "soh": null,
    "remarques": "",
    "lien": "https://www.ev-market.fr/voitures-electriques/77787-tesla-model-3-350-awd-long-range-2",
    "score": 64.7,
    "prixTotal": 28990,
    "localisation": "France (sur place)",
    "optionEap": "EAP inclus ✓",
    "covering": 0,
    "budgetToutCompris": 28990,
    "fsd24": 1176,
    "budget2ansFsd": 30166,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a005",
    "prix": 30990,
    "origine": "France (courtier)",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen (probable)",
    "modele": "Performance",
    "couleur": "Noir",
    "coutImportation": 1500,
    "kilometrage": 19000,
    "interieur": "",
    "soh": null,
    "remarques": "Perf 513ch faible km — courtier TransakAuto (frais 890€, hors CG)",
    "lien": "https://www.leboncoin.fr/ad/voitures/3222240940",
    "score": 60.6,
    "prixTotal": 32490,
    "localisation": "Villefranche-de-Lauragais ~900 km",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 0,
    "budgetToutCompris": 32490,
    "fsd24": 2376,
    "budget2ansFsd": 34866,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a006",
    "prix": 29550,
    "origine": "France (import)",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen (probable)",
    "modele": "Performance",
    "couleur": "noire",
    "coutImportation": 1500,
    "kilometrage": 42500,
    "interieur": "Noir",
    "soh": null,
    "remarques": "Fausse 'France': véhicule importé, non immatriculé FR",
    "lien": "https://www.leboncoin.fr/ad/voitures/3209638380",
    "score": 49.7,
    "prixTotal": 31050,
    "localisation": "Vendeur importateur Mérignac ~900 km (COC + carte grise fournis)",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 0,
    "budgetToutCompris": 31050,
    "fsd24": 2376,
    "budget2ansFsd": 33426,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a007",
    "prix": 31990,
    "origine": "Allemagne",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen (probable)",
    "modele": "Performance",
    "couleur": "Grise",
    "coutImportation": 1850,
    "kilometrage": 35900,
    "interieur": "Noir",
    "soh": null,
    "remarques": "(autoscout24.de)",
    "lien": "https://www.leparking.fr/voiture-occasion-detail/tesla-model-3-performance/performance-dual-awd/9XBJ028Q.html",
    "score": 47.8,
    "prixTotal": 33840,
    "localisation": "Ahaus (NRW) ~525 km +livr.",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 0,
    "budgetToutCompris": 33840,
    "fsd24": 2376,
    "budget2ansFsd": 36216,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a008",
    "prix": 33499,
    "origine": "Allemagne",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen (probable)",
    "modele": "Performance",
    "couleur": "Blanc",
    "coutImportation": 1500,
    "kilometrage": 36196,
    "interieur": "Noir",
    "soh": 0.94,
    "remarques": "Blanche Performance, SOH 94 (mobile.de)",
    "lien": "https://suchen.mobile.de/auto-inserat/x/455819977.html",
    "score": 45.3,
    "prixTotal": 34999,
    "localisation": "Gaggenau (Karlsruhe) ~60 km",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 0,
    "budgetToutCompris": 34999,
    "fsd24": 2376,
    "budget2ansFsd": 37375,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a009",
    "prix": 33490,
    "origine": "Allemagne",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen (probable)",
    "modele": "LR AWD",
    "couleur": "Blanc",
    "coutImportation": 1500,
    "kilometrage": 19900,
    "interieur": "Noir",
    "soh": null,
    "remarques": "Blanche Base, usine Shanghai, TRÈS faible km — covering prévu",
    "lien": "https://suchen.mobile.de/auto-inserat/x/458371122.html",
    "score": 42.2,
    "prixTotal": 34990,
    "localisation": "Linkenheim (Karlsruhe) ~90 km",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 2500,
    "budgetToutCompris": 37490,
    "fsd24": 2376,
    "budget2ansFsd": 39866,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a010",
    "prix": 33999,
    "origine": "Allemagne",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen (probable)",
    "modele": "Performance",
    "couleur": "Blanc",
    "coutImportation": 1500,
    "kilometrage": 39617,
    "interieur": "Noir",
    "soh": 0.93,
    "remarques": "Blanche Performance, Giga 1ère main, SOH 93 (mobile.de)",
    "lien": "https://suchen.mobile.de/auto-inserat/x/459098599.html",
    "score": 42.2,
    "prixTotal": 35499,
    "localisation": "Gaggenau (Karlsruhe) ~60 km",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 0,
    "budgetToutCompris": 35499,
    "fsd24": 2376,
    "budget2ansFsd": 37875,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a011",
    "prix": 29945,
    "origine": "Allemagne",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen (probable)",
    "modele": "Performance",
    "couleur": "noire",
    "coutImportation": 1500,
    "kilometrage": 55100,
    "interieur": "Noir",
    "soh": null,
    "remarques": "",
    "lien": "https://suche.pkw.de/fahrzeuge/details/906113843042163079",
    "score": 41.5,
    "prixTotal": 31445,
    "localisation": "Fulda (Hesse) ~260 km",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 0,
    "budgetToutCompris": 31445,
    "fsd24": 2376,
    "budget2ansFsd": 33821,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a012",
    "prix": 32690,
    "origine": "Allemagne",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen (probable)",
    "modele": "LR AWD",
    "couleur": "Argent",
    "coutImportation": 1500,
    "kilometrage": 36689,
    "interieur": "Noir",
    "soh": null,
    "remarques": "Toit pano (autoscout24.de)",
    "lien": "https://www.leparking.fr/voiture-occasion-detail/tesla-model-3-grande-autonomie/long-range-dual-75-kwh-awd-pano-s-dach-a/HC9HUK7C.html",
    "score": 39.1,
    "prixTotal": 34190,
    "localisation": "Krefeld (NRW) ~380 km",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 0,
    "budgetToutCompris": 34190,
    "fsd24": 2376,
    "budget2ansFsd": 36566,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a013",
    "prix": 31900,
    "origine": "Allemagne",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen (probable)",
    "modele": "LR AWD",
    "couleur": "Blanc",
    "coutImportation": 1500,
    "kilometrage": 31300,
    "interieur": "Noir",
    "soh": null,
    "remarques": "Blanche Base, usine Shanghai, faible km — covering prévu",
    "lien": "https://suchen.mobile.de/auto-inserat/x/458464119.html",
    "score": 38.8,
    "prixTotal": 33400,
    "localisation": "Linkenheim (Karlsruhe) ~90 km",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 2500,
    "budgetToutCompris": 35900,
    "fsd24": 2376,
    "budget2ansFsd": 38276,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a014",
    "prix": 31499,
    "origine": "Allemagne",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen (probable)",
    "modele": "Performance",
    "couleur": "Noir",
    "coutImportation": 1500,
    "kilometrage": 55821,
    "interieur": "Noir",
    "soh": null,
    "remarques": "",
    "lien": "https://suchen.mobile.de/auto-inserat/x/458401010.html",
    "score": 37.8,
    "prixTotal": 32999,
    "localisation": "Ergolding (Bavière) ~430 km",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 0,
    "budgetToutCompris": 32999,
    "fsd24": 2376,
    "budget2ansFsd": 35375,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a015",
    "prix": 28250,
    "origine": "Allemagne",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen (probable)",
    "modele": "LR AWD",
    "couleur": "Bleue",
    "coutImportation": 1500,
    "kilometrage": 55900,
    "interieur": "Noir",
    "soh": null,
    "remarques": "",
    "lien": "https://www.kleinanzeigen.de/s-anzeige/x/3371565405",
    "score": 37,
    "prixTotal": 29750,
    "localisation": "Bielefeld (NRW) ~470 km",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 0,
    "budgetToutCompris": 29750,
    "fsd24": 2376,
    "budget2ansFsd": 32126,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a016",
    "prix": 29989,
    "origine": "Allemagne",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen (probable)",
    "modele": "LR AWD",
    "couleur": "Blanc",
    "coutImportation": 1500,
    "kilometrage": 43871,
    "interieur": "Noir",
    "soh": null,
    "remarques": "Blanche Base, bonne affaire — covering prévu",
    "lien": "https://suchen.mobile.de/auto-inserat/x/458071323.html",
    "score": 35.3,
    "prixTotal": 31489,
    "localisation": "Fernwald (Gießen) ~230 km",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 2500,
    "budgetToutCompris": 33989,
    "fsd24": 2376,
    "budget2ansFsd": 36365,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a017",
    "prix": 32490,
    "origine": "Allemagne",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen (probable)",
    "modele": "Performance",
    "couleur": "Blanc",
    "coutImportation": 1500,
    "kilometrage": 58277,
    "interieur": "Noir",
    "soh": null,
    "remarques": "Blanche Performance (mobile.de)",
    "lien": "https://suchen.mobile.de/auto-inserat/x/459459751.html",
    "score": 34.3,
    "prixTotal": 33990,
    "localisation": "Wurmberg (Pforzheim) ~90 km",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 0,
    "budgetToutCompris": 33990,
    "fsd24": 2376,
    "budget2ansFsd": 36366,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a018",
    "prix": 32890,
    "origine": "Allemagne",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen (probable)",
    "modele": "Performance",
    "couleur": "Blanc",
    "coutImportation": 1500,
    "kilometrage": 57699,
    "interieur": "Noir",
    "soh": null,
    "remarques": "Blanche Performance (mobile.de)",
    "lien": "https://suchen.mobile.de/auto-inserat/x/454726704.html",
    "score": 33.8,
    "prixTotal": 34390,
    "localisation": "Wurmberg (Pforzheim) ~90 km",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 0,
    "budgetToutCompris": 34390,
    "fsd24": 2376,
    "budget2ansFsd": 36766,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a019",
    "prix": 31900,
    "origine": "Allemagne",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen (probable)",
    "modele": "LR AWD",
    "couleur": "Noir",
    "coutImportation": 1500,
    "kilometrage": 48800,
    "interieur": "Noir",
    "soh": null,
    "remarques": "Usine Shanghai, 1ère main (autoscout24.de)",
    "lien": "https://www.leparking.fr/voiture-occasion-detail/tesla-model-3-grande-autonomie/long-range-dual-awd-shanghai-1-hand/3A3X0GK1.html",
    "score": 33.6,
    "prixTotal": 33400,
    "localisation": "Linkenheim (Karlsruhe) ~90 km",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 0,
    "budgetToutCompris": 33400,
    "fsd24": 2376,
    "budget2ansFsd": 35776,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a020",
    "prix": 30990,
    "origine": "France",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen (probable)",
    "modele": "LR AWD",
    "couleur": "",
    "coutImportation": 0,
    "kilometrage": 57850,
    "interieur": "",
    "soh": null,
    "remarques": "MeilleurOccas, 1ère main, couleur non précisée (à vérifier) — NOUVELLE (leboncoin)",
    "lien": "https://www.leboncoin.fr/ad/voitures/3201105630",
    "score": 33.3,
    "prixTotal": 30990,
    "localisation": "Méteren (Nord) France ~500 km",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 0,
    "budgetToutCompris": 30990,
    "fsd24": 2376,
    "budget2ansFsd": 33366,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a021",
    "prix": 31490,
    "origine": "France",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen probable (à confirmer)",
    "modele": "LR AWD",
    "couleur": "Bleue",
    "coutImportation": 0,
    "kilometrage": 57000,
    "interieur": "Noir",
    "soh": 0.95,
    "remarques": "Plusieurs impacts carrosserie",
    "lien": "https://www.leboncoin.fr/ad/voitures/3207386226",
    "score": 32.7,
    "prixTotal": 31490,
    "localisation": "France (sur place)",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 0,
    "budgetToutCompris": 31490,
    "fsd24": 2376,
    "budget2ansFsd": 33866,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a022",
    "prix": 35990,
    "origine": "France",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen (probable)",
    "modele": "Performance",
    "couleur": "Blanc",
    "coutImportation": 0,
    "kilometrage": 53990,
    "interieur": "",
    "soh": null,
    "remarques": "Blanche Performance, vendeur local Hoenheim",
    "lien": "https://www.leboncoin.fr/ad/voitures/3188961544",
    "score": 32.7,
    "prixTotal": 35990,
    "localisation": "Hoenheim (Strasbourg) ~5 km",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 0,
    "budgetToutCompris": 35990,
    "fsd24": 2376,
    "budget2ansFsd": 38366,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a023",
    "prix": 31535,
    "origine": "Allemagne",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen",
    "modele": "LR AWD",
    "couleur": "Grise",
    "coutImportation": 1500,
    "kilometrage": 52674,
    "interieur": "Blanc",
    "soh": 0.94,
    "remarques": "",
    "lien": "https://suchen.mobile.de/auto-inserat/x/459424429.html",
    "score": 32.1,
    "prixTotal": 33035,
    "localisation": "Seesen (Basse-Saxe) ~460 km",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 0,
    "budgetToutCompris": 33035,
    "fsd24": 2376,
    "budget2ansFsd": 35411,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a024",
    "prix": 31490,
    "origine": "Belgique",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen (probable)",
    "modele": "LR AWD",
    "couleur": "grise",
    "coutImportation": 1500,
    "kilometrage": 53000,
    "interieur": "Noir",
    "soh": null,
    "remarques": "",
    "lien": "https://www.autoscout24.be/fr/offres/tesla-model-3-model-3-78-kwh-awd-long-range-dual-motor-366kw-garantie-tesla-electrique-gris-cat_ma51520mo74665-9dd85577-30f9-4766-a89f-525df80e1b33",
    "score": 32,
    "prixTotal": 32990,
    "localisation": "Gembloux (BE) ~370 km",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 0,
    "budgetToutCompris": 32990,
    "fsd24": 2376,
    "budget2ansFsd": 35366,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a025",
    "prix": 29389,
    "origine": "Allemagne",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen (probable)",
    "modele": "LR AWD",
    "couleur": "Blanc",
    "coutImportation": 1500,
    "kilometrage": 52626,
    "interieur": "Noir",
    "soh": null,
    "remarques": "Blanche Base, la moins chère — covering prévu",
    "lien": "https://suchen.mobile.de/auto-inserat/x/458482100.html",
    "score": 31.4,
    "prixTotal": 30889,
    "localisation": "Fernwald (Gießen) ~230 km",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 2500,
    "budgetToutCompris": 33389,
    "fsd24": 2376,
    "budget2ansFsd": 35765,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a026",
    "prix": 29450,
    "origine": "Allemagne",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen probable (à confirmer)",
    "modele": "LR AWD",
    "couleur": "grise",
    "coutImportation": 1500,
    "kilometrage": 61455,
    "interieur": "Noir",
    "soh": null,
    "remarques": "",
    "lien": "https://suchen.mobile.de/auto-inserat/x/459736641.html",
    "score": 31.2,
    "prixTotal": 30950,
    "localisation": "Bad Kissingen (Bavière) ~250 km",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 0,
    "budgetToutCompris": 30950,
    "fsd24": 2376,
    "budget2ansFsd": 33326,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a027",
    "prix": 33880,
    "origine": "Allemagne",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen (probable)",
    "modele": "LR AWD",
    "couleur": "Noir",
    "coutImportation": 1500,
    "kilometrage": 49200,
    "interieur": "Noir",
    "soh": 0.94,
    "remarques": "Ryzen confirmé, attelage, jantes 19\" (mobile.de)",
    "lien": "https://suchen.mobile.de/auto-inserat/x/456458668.html",
    "score": 29.3,
    "prixTotal": 35380,
    "localisation": "Albbruck (Bade-W.) ~150 km",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 0,
    "budgetToutCompris": 35380,
    "fsd24": 2376,
    "budget2ansFsd": 37756,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a028",
    "prix": 33227,
    "origine": "Allemagne",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen (probable)",
    "modele": "LR AWD",
    "couleur": "Noir",
    "coutImportation": 1500,
    "kilometrage": 51727,
    "interieur": "Noir",
    "soh": null,
    "remarques": "Autopilot, attelage (mobile.de)",
    "lien": "https://www.leparking.fr/voiture-occasion-detail/tesla-model-3-grande-autonomie/long-range-a-pilot-pr-int-ahk/JYMC711F.html",
    "score": 29.2,
    "prixTotal": 34727,
    "localisation": "Eschborn (Francfort) ~220 km",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 0,
    "budgetToutCompris": 34727,
    "fsd24": 2376,
    "budget2ansFsd": 37103,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a029",
    "prix": 29980,
    "origine": "France",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen (confirmé)",
    "modele": "LR AWD",
    "couleur": "Grise",
    "coutImportation": 0,
    "kilometrage": 69667,
    "interieur": "noir",
    "soh": 0.9,
    "remarques": "SOH 90% (source autoscout24.de identique)",
    "lien": "https://suchen.mobile.de/auto-inserat/x/458030246.html",
    "score": 28.4,
    "prixTotal": 29980,
    "localisation": "France (sur place)",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 0,
    "budgetToutCompris": 29980,
    "fsd24": 2376,
    "budget2ansFsd": 32356,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a030",
    "prix": 29599,
    "origine": "Allemagne",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen (probable)",
    "modele": "LR AWD",
    "couleur": "Bleue",
    "coutImportation": 1900,
    "kilometrage": 64506,
    "interieur": "Blanc",
    "soh": null,
    "remarques": "",
    "lien": "https://suchen.mobile.de/auto-inserat/x/456871610.html",
    "score": 28.3,
    "prixTotal": 31499,
    "localisation": "Eilenburg (Leipzig) ~570 km +livr.",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 0,
    "budgetToutCompris": 31499,
    "fsd24": 2376,
    "budget2ansFsd": 33875,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a031",
    "prix": 30900,
    "origine": "France",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen (probable)",
    "modele": "LR AWD",
    "couleur": "Noir",
    "coutImportation": 0,
    "kilometrage": 67125,
    "interieur": "Noir",
    "soh": null,
    "remarques": "",
    "lien": "https://suchen.mobile.de/auto-inserat/x/453859399.html",
    "score": 28,
    "prixTotal": 30900,
    "localisation": "France (sur place)",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 0,
    "budgetToutCompris": 30900,
    "fsd24": 2376,
    "budget2ansFsd": 33276,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a032",
    "prix": 29900,
    "origine": "Allemagne",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen (probable)",
    "modele": "LR AWD",
    "couleur": "grise",
    "coutImportation": 1500,
    "kilometrage": 66070,
    "interieur": "Blanc",
    "soh": null,
    "remarques": "",
    "lien": "https://suchen.mobile.de/auto-inserat/x/455711830.html",
    "score": 27.6,
    "prixTotal": 31400,
    "localisation": "Maßbach (Bavière) ~250 km",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 0,
    "budgetToutCompris": 31400,
    "fsd24": 2376,
    "budget2ansFsd": 33776,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a033",
    "prix": 30107,
    "origine": "Allemagne",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen (probable)",
    "modele": "LR AWD",
    "couleur": "Blanc",
    "coutImportation": 1500,
    "kilometrage": 58597,
    "interieur": "Noir",
    "soh": null,
    "remarques": "Blanche Base, toit pano — covering prévu",
    "lien": "https://suchen.mobile.de/auto-inserat/x/458594797.html",
    "score": 26.4,
    "prixTotal": 31607,
    "localisation": "Riedstadt (Francfort) ~200 km",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 2500,
    "budgetToutCompris": 34107,
    "fsd24": 2376,
    "budget2ansFsd": 36483,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a034",
    "prix": 31990,
    "origine": "France",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen (probable)",
    "modele": "LR AWD",
    "couleur": "Noir",
    "coutImportation": 0,
    "kilometrage": 69938,
    "interieur": "",
    "soh": 0.92,
    "remarques": "LR AWD, SOH 92% annoncé (leboncoin)",
    "lien": "https://www.leboncoin.fr/ad/voitures/3218623945",
    "score": 24.1,
    "prixTotal": 31990,
    "localisation": "Dijon ~250 km",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 0,
    "budgetToutCompris": 31990,
    "fsd24": 2376,
    "budget2ansFsd": 34366,
    "statut": "À suivre",
    "favori": false
  },
  {
    "id": "a035",
    "prix": 32500,
    "origine": "Allemagne",
    "autopilot": "🥉 Base",
    "processeur": "Ryzen (probable)",
    "modele": "LR AWD",
    "couleur": "Noir",
    "coutImportation": 1900,
    "kilometrage": 67224,
    "interieur": "Noir",
    "soh": null,
    "remarques": "AMD Ryzen confirmé (autoscout24.de)",
    "lien": "https://www.leparking.fr/voiture-occasion-detail/tesla-model-3-grande-autonomie/model-3-long-range-dual-motor-amd-ryzen/LX9LWUG8.html",
    "score": 20.7,
    "prixTotal": 34400,
    "localisation": "Emsbüren (NRW) ~540 km +livr.",
    "optionEap": "À souscrire (abo ~50-70€/mois)*",
    "covering": 0,
    "budgetToutCompris": 34400,
    "fsd24": 2376,
    "budget2ansFsd": 36776,
    "statut": "À suivre",
    "favori": false
  }
];
